name: CI
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop", "main"]

env:
  RAILS_ENV: test
  RAILS_MAX_THREADS: 5

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        # Pode adicionar mais versões do Ruby se necessário
        ruby-version: ['3.4.5']

    env:
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/nexti_talent_test"
      RAILS_CACHE_DATABASE_URL: "postgres://postgres:postgres@localhost:5432/nexti_talent_test_cache"
      RAILS_QUEUE_DATABASE_URL: "postgres://postgres:postgres@localhost:5432/nexti_talent_test_queue"
      RAILS_CABLE_DATABASE_URL: "postgres://postgres:postgres@localhost:5432/nexti_talent_test_cable"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup databases
        run: |
          bin/rails db:create
          bin/rails db:migrate
          # Configurar bancos de dados secundários do Rails 8
          bin/rails db:create:cache
          bin/rails db:migrate:cache
          bin/rails db:create:queue
          bin/rails db:migrate:queue
          bin/rails db:create:cable
          bin/rails db:migrate:cable

      - name: Precompile assets
        run: |
          bin/rails assets:precompile

      - name: Run tests
        run: |
          bundle exec rspec --format progress --format RspecJunitFormatter --out test-results/rspec.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/

  lint:
    runs-on: ubuntu-latest
    
    env:
      RAILS_ENV: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true

      - name: Cache bundler
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Instalar dependências
        run: bundle install

      - name: Security audit dependencies
        run: bundle exec bundler-audit --update

      - name: Security audit application code  
        run: bundle exec brakeman -q -w2

      - name: Lint Ruby files
        run: bundle exec rubocop --parallel

  system-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/nexti_talent_test"
      RAILS_CACHE_DATABASE_URL: "postgres://postgres:postgres@localhost:5432/nexti_talent_test_cache"
      RAILS_QUEUE_DATABASE_URL: "postgres://postgres:postgres@localhost:5432/nexti_talent_test_queue"
      RAILS_CABLE_DATABASE_URL: "postgres://postgres:postgres@localhost:5432/nexti_talent_test_cable"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true

      - name: Setup databases
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:create:cache
          bin/rails db:migrate:cache
          bin/rails db:create:queue
          bin/rails db:migrate:queue
          bin/rails db:create:cable
          bin/rails db:migrate:cable

      - name: Precompile assets
        run: bin/rails assets:precompile

      - name: Run system tests
        run: bundle exec rspec spec/system/

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: tmp/screenshots/